import { test, expect, login, screenshot } from '../fixtures'
test('administrator creates a requester with first-login restriction', async ({ page, accounts }) => {
  await login(page, accounts.admin)
  await expect(page).toHaveURL(/\/staff\/tickets$/)
  await page.goto('/admin/users')
  await expect(page.getByRole('heading', { name: 'User Management' })).toBeVisible()
  await screenshot(page, '06-admin-user-management')
  await page.getByRole('button', { name: '+ New User' }).click()
  await expect(page.getByText('Create New User')).toBeVisible()
  await page.getByLabel('Full Name', { exact: true }).fill('E2E Created Requester')
  await page.locator('#user-email').fill(accounts.createdEmail)
  await page.getByLabel('Initial Password', { exact: true }).fill('initial-test-123')
  await screenshot(page, '07-admin-create-user-modal')
  await page.getByRole('button', { name: 'Save User' }).click()
  const row = page.getByRole('row').filter({ hasText: accounts.createdEmail })
  await expect(row).toBeVisible()
  await expect(row).toContainText('Needs Password Reset')
  await screenshot(page, '09-admin-created-user')
})
